# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.define :rails_sandbox do |node|
    node.vm.box = 'centos64_6_8'
    node.vm.box_url = 'http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.8_chef-provisionerless.box'
    node.vm.network 'private_network', ip: '192.168.55.10'
    node.vm.provision :shell, path: '../utils/setup_rbenv.sh', args: '2.4.1'
    node.vm.provision :shell, path: '../utils/make_ready4rails.sh'
    node.vm.provision :shell, path: '../utils/setup_netrc_skelton.sh'
    node.vm.provision :shell, path: '../utils/setup_mysql5_6.sh'
    node.vm.provision :shell, path: '../utils/setup_vim.sh'
    node.vm.provision :shell, path: '../utils/setup_libcurl.sh'
    node.vm.synced_folder '~/projects/', '/projects'
  end
end
