# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.define :rails_sandbox do |node|
    node.vm.box = 'centos64_6_8'
    node.vm.box_url = 'http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.8_chef-provisionerless.box'
    node.vm.network 'private_network', ip: '192.168.55.30', guest: 8080, host:8080
    node.vm.provision :shell, path: '../utils/setup_postgress.sh'
    node.vm.provision :shell, path: '../utils/setup_rbenv.sh'
    node.vm.provision :shell, path: '../utils/make_ready4rails.sh'
    node.vm.provision :shell, path: '../utils/setup_netrc_skelton.sh'
    node.vm.provision :shell, path: '../utils/setup_heroku_cli.sh'
    node.vm.provision :shell, inline: 'rpm -ivh http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm'
    node.vm.provision :shell, inline: 'yum install -y nginx'
    node.vm.provision :shell, inline: 'cp -p /vagrant/default.conf /etc/nginx/conf.d/'
    node.vm.provision :shell, inline: 'cp -p /vagrant/nginx.conf /etc/nginx/'
  end
end
